[package]
name = "aegis"
version = "1.0.1"
authors = []

[addresses]
aegis_addr="48121ae8a5bb7e2875d1b7f41508f288c3f68514a3c4b4cb605024b3f8ccb36b"

[dev-addresses]

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "mainnet"
subdir = "cedra-framework"

[dev-dependencies]
