[package]
name = "aegis"
version = "1.0.1"
authors = []

[addresses]
aegis_addr="250c8136752bdabd878ae50883436ef46842edefbd825ee7c3ddfc7391aebaeb"

[dev-addresses]

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "mainnet"
subdir = "cedra-framework"

[dev-dependencies]
