[package]
name = "aegis"
version = "1.0.1"
authors = []

[addresses]
aegis_addr="6a3dec044b92d5a5367513a4bcf5287000eaaafb906c81339fde4298f3ff9175"

[dev-addresses]

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "mainnet"
subdir = "cedra-framework"

[dev-dependencies]
